### ISSUE TITLE
Refresh NuGet Release

### ISSUE THREAD

**Issue by mpolitze** [ap0llo/changelog#179]
Hi!

Thank you for this handy tool. I am currently migrating our build system to dotnet5 and it would help a lot.

In your repo I can see that you did quite some changes since the last release to NuGet, especially dotnet5 targets. 

Would you mind to trigger a new release there?

Thanks!

**Comment by ap0llo** [comment]
Glad to hear this tool is useful to you.

I just published release [0.3.341](https://github.com/ap0llo/changelog/releases/tag/v0.3.341), it should become available on NuGet.org within the hour (it takes a moment for new uploads to nuget.org to become visible)
