### ISSUE TITLE
💡 Idea: Allow creating multiple change log entries from a single commit

### ISSUE THREAD

**Issue by ap0llo** [ap0llo/changelog#220]
Allow writing multiple change log entries in a single commit (e.g. separated by `---`).

While this is not compliant with the conventional commits specification, this might be useful in situations where multiple features are implemented at once (which cannot always be avoided)

**Comment by Crown0815** [comment]
Just my two cents: I understand the temptation, but one of the motivations behind using conventional commits, in my opinion, is to make small atomic commits. These atomic commits, by definition, should not introduce more than one feature/bug fix/etc..

**Comment by ap0llo** [comment]
Yes, this was an idea I had back in the day - and probably not a very good one. 😅

Thinking about it, it would also break the linking between change log entries that's already implemented because changelog uses the commit id to identify entries and assumes it is unique.
